name: 代理池检查
on: 
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TC_GH_TOKEN }}
    - name: 设置时区
      run: |
        sudo timedatectl set-timezone 'UTC'
    - name: 测试代理池
      env:
        TC_GH_REPO: ${{ github.repository }}
        TC_GH_TOKEN: ${{ secrets.TC_GH_TOKEN }}
        TC_GH_USER: ${{ secrets.TC_GH_USER }}
        TC_GH_EMAIL: ${{ secrets.TC_GH_EMAIL }}
        TC_SECRET_ID: ${{ secrets.TC_SECRET_ID }}
        TC_SECRET_KEY: ${{ secrets.TC_SECRET_KEY }}
        TC_POOL_URL: ${{ secrets.TC_POOL_URL }}
      run: |
        ulimit -SHn 65536
        sudo bash -c "echo 1 >/proc/sys/net/ipv4/tcp_tw_reuse"
        ./start.sh run
    - name: 提交订阅更新
      run: |
        git config --global user.email "hansyow@gmail.com"
        git config --global user.name "hansyao"      
        git pull
        git add subscribe/
        git commit -m "订阅更新(by github actions)"
        git push -u origin master