name: 发布腾讯云函数
on: 
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TC_GH_TOKEN }}
    - name: 设置时区
      run: |
        sudo timedatectl set-timezone 'UTC'
    - name: 发布函数
      env:
        TC_GH_REPO: ${{github.repository}}
        TC_GH_TOKEN: ${{ secrets.TC_GH_TOKEN }}
        TC_GH_USER: ${{ secrets.TC_GH_USER }}
        TC_GH_EMAIL: ${{ secrets.TC_GH_EMAIL }}
        TC_SECRET_ID: ${{ secrets.TC_SECRET_ID }}
        TC_SECRET_KEY: ${{ secrets.TC_SECRET_KEY }}
        TC_POOL_URL: ${{ secrets.TC_POOL_URL }}
      run: |
        sed -i s/^PLATFORM\=./PLATFORM\=1/g env.sh
        sed -i s/^PLATFORM\=./PLATFORM\=1/g Actions/pool.sh
        sed -i s/^TARGET_NODES\=.*/TARGET_NODES\=200/g Actions/pool.sh
        sed -i s/^TIMEOUT\=.*/TIMEOUT\=1/g Actions/pool.sh
        sed -i s/^BLOCK_SIZE\=.*/BLOCK_SIZE\=200/g Actions/pool.sh
        sed -i s/^THREADNUMBER\=.*/THREADNUMBER\=15/g Actions/pool.sh
        sed -i s/^THREADNUMBER2\=.*/THREADNUMBER2\=5/g Actions/pool.sh
        echo "发布函数层依赖"
        if [[ $(./tencent_cf_deploy.sh ListLayerVersions pool_check_layer | jq -r '.Response.LayerVersions[].Status' | head -n 1) != 'Active' ]]; then 
          ./tencent_cf_deploy.sh PublishLayerVersion pool_check_layer
          sleep 5
        fi
        export LayerVersion=$(./tencent_cf_deploy.sh ListLayerVersions pool_check_layer | jq -r '.Response.LayerVersions[].LayerVersion' | head -n 1)
        echo "发布函数"
        ./tencent_cf_deploy.sh CreateFunction pool_checker pool_check_layer ${LayerVersion}
